### ISSUE TITLE
jekyll upgrade

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/mango-is-website#15]
Make the site compatible with of jekyll version 3.x

**Comment by webketje** [comment]
Updated: 892f9b6566e2cdef37d97730dcc8194728869403
No breaking changes at first sight, only character replacements

**Comment by mef** [comment]
is this to be tested yet? tag is missing.

**Comment by webketje** [comment]
Not to forget (& not in this commit ofc.):
- update `pygments: true` to `highlighter: pygments` in local `_config.yml`
- update jekyll to 3.x

**Comment by mef** [comment]
>update pygments: true to highlighter: pygments in local _config.yml

this should be changed inside the sample config file.

**Comment by mef** [comment]
code highlighting does not work for me.

The `jekyll build` runs well, but then I get the following instead of the code blocks:

`<p>Liquid error: pygments</p>`

This can be seen inside this article for example: `/_site/blog/engineering/pre-render-d3-js-charts-at-server-side.html`

@webketje, thanks for letting me know whether this is also the case in your setup. Maybe it's just my version of ruby and/or pygments which is faulty.

* ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
* jekyll (3.0.0.pre.beta8, 2.5.3)
* pygments.rb (0.6.3)

**Comment by mef** [comment]
testing result: I've done a diff between this version and the previous one. Except for the code's  syntax highlighter, everything looks good.

**Comment by webketje** [comment]
Tested and syntax highlighting works both for `jekyll serve` (local server) and `jekyll build` (generated files in _site). My setup is slightly different though:
* ruby 2.1.0
* pygments.rb (0.6.0)

**Comment by mef** [comment]
Ok, Thanks, good to know.I'm setting up another machine in the mean time, will check whether the code generates well in there.

**Comment by mef** [comment]
minor issue: I sometimes have the following warnings when running `jekyll serve`:

     Build Warning: Layout 'none' requested in blog/feed/index.xml does not exist.
     Build Warning: Layout 'none' requested in blog/engineering/feed/index.xml does not exist.
     Build Warning: Layout 'none' requested in blog/business/feed/index.xml does not exist.

**Comment by mef** [comment]
the code highlighting error is stil here for me (`Liquid error: pygments`). 

Downgrading to pygments 0.6.0 didn't solve the problem.

Which version of liquid is installed in your machine? I'm on liquid (3.0.6)

**Comment by mef** [comment]
it's worth noting that exactly the same error happens if I switch to rouge syntax highlighter.

**Comment by webketje** [comment]
@mef about the minor issue; yes,  I get that all the time too (together with `Error: Marshal data too short...`). Guess the parser has become stricter.My Liquid version is 3.0.4. Never had any problems with pygments.

**Comment by mef** [comment]
finally switching to hexo instead
