### ISSUE TITLE
Large files fail

### ISSUE THREAD

**Issue by Bert-Jan-Stroop** [Mango-information-systems/mango-is-website#164]
Hi, I tried converting a larger file (400 MB) but when i convert i only receive a JSON with the last couple of documents.

**Comment by mef** [comment]
Hey, thanks for reporting this problem.

Was any error message or warning displayed?

Normally, two lines are displayed on screen just as a preview. When you click on "convert", the data processing happens in the background, you should be patient, then a download hyperlink appears. Did you reach this step?

I just tried with a 350+MB CSV file. It crashed on Google Chrome, but worked well on Firefox.

**Comment by mef** [comment]
Hi @Bert-Jan-Stroop, are you still experiencing the problem during conversion of large CSV files? If so, thanks for replying to the questions from previous message.

**Comment by Bert-Jan-Stroop** [comment]
Hi Medhi,

We used your services on a single occassion. When we got some problems with
big csv's we created our own local application to handle it, and we are
currently using that. So I have no further information about the state of
the issue, since I didn't try it since.

Kind Regards

Bert-Jan Stroop

2018-04-02 17:49 GMT+02:00 Mehdi El Fadil <notifications@github.com>:

**Comment by mef** [comment]
Ok, thanks for the update.

I'll close the issue then.
