### ISSUE TITLE
Load scripts from CDN with fallback

### ISSUE THREAD

**Issue by webketje** [Mango-information-systems/mango-is-website#18]
The following assets should be loaded from a CDN (both js and cdn), with fallback to local copy of the assets in case of error:

* jQuery
* foundation
* d3.js
* reveal.js

- [x] use a cdn to load the assets
- [x] fallback to local version of the assets in case of CDN unavailability or error
- [x] make sure that the offline version of the site works (http://mango-is.com/tool/csv-to-json.html)

(issue edited by @mef)

**Comment by mef** [comment]
comment from @webketje :


____________________________________

3 possible approaches, which one do you prefer?

**1. Custom function in `<head>`, inline `onerror` tags**

````````````
function jsFallback(target) {
  target.src = 'js/' + target.getAttribute('data-lib') + '.js';
}
```````````` 
The script tags would look like this (eg. for jQuery) 
```````````
<script src="http://cdn/link/jquery.js" onerror="jsFallback(this)" data-lib="jquery"></script>
``````````````
(ofc. you can also just loop all script tags and attach onerror event in JS)

**2. Testing for an object existing only in the script**

``````````````
<script src="http://cdn/link/jquery.js"></script>
<script>if (!window.jQuery) { document.write('...') }</script>
`````````````` 

**CON:** Most popular solution, but can get tedious when you have a lot of objects to check.

**3. Using a library**
Eg, http://fallback.io/

**Comment by mef** [comment]
I'll investigate and let you know

**Comment by webketje** [comment]
@mef good news! Because Foundation requires Modernizr, and Modernizr has its own version of yepnope.js (script loader) built in, [we should be able to load them with `Modernizr.load()`](http://stackoverflow.com/questions/1014203/best-way-to-use-googles-hosted-jquery-but-fall-back-to-my-hosted-library-on-go#answer-11215592)

**Comment by mef** [comment]
Great!

**Comment by webketje** [comment]
@mef Update: implemented through 'basic' but most reliable way. (`Obj || document.write('script...`).
**Important:** When you do a Foundation build, you will have to modify the assets loaded here. Foundation modules are loaded separately, should be combined into one file. The modules used are Magellan Sticky Nav (foundation.topbar), foundation.tooltip (only used in d3.js blog articles), and foundation.reveal (modal used for contact form popup).

**Comment by mef** [comment]
canceled / postponed change
