### ISSUE TITLE
markup issue in authors page

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/mango-is-website#21]
The blog authors page mixes markdown and html, for articles titles line, in consequence mad ids are created for the h4 tags:

![screenshot - 250715 - 11 03 06](https://cloud.githubusercontent.com/assets/925443/8888790/c0601b20-32bc-11e5-982e-798070b4d99d.png)

Fact is that we don't need any Id at all for these headings.

todo:

- [x] fix the issue inside file: `/blog/authors/index.md`
- [x] check that the other index pages (one at the root of /blog, and one per category) don't have a similar problem

**Comment by webketje** [comment]
Some lay-out issues persist (but this is for after the Foundation base migration)

**Comment by mef** [comment]
related to the canceled switch to foundation - skeleton to be used instead
