### ISSUE TITLE
Migrate Livefyre => Disqus comments

### ISSUE THREAD

**Issue by webketje** [Mango-information-systems/mango-is-website#22]
For reference:

* [LiveFyre API](http://answers.livefyre.com/developers/api-reference/)
* [Disqus API](https://disqus.com/api/docs/)
* [Problems related to comment migration to Disqus](https://help.disqus.com/customer/portal/questions/6530364-why-are-imported-comments-not-showing-on-the-blog-post-)

**Comment by mef** [comment]
thanks!

**Comment by mef** [comment]
duplicates #34
