### ISSUE TITLE
Decide on icon font

### ISSUE THREAD

**Issue by webketje** [Mango-information-systems/mango-is-website#24]
I've come to the conclusion that Foundation icon font is a bad choice. Check out their repo's [code contributions](https://github.com/zurb/foundation-icons/graphs/code-frequency), they stopped 3 years ago, and last activity on issues seems to be in 2013. We can still just keep the icons, but I see they have much less than Font Awesome (or others). There are no `chevron` or `angle` icons (used in your csv-to-json tool). I can only use bland arrows.

Please let me know if this alters your icon font choice. (and also which folder to put the iconfont files in)

**Comment by mef** [comment]
related to the canceled switch to foundation - skeleton to be used instead
