### ISSUE TITLE
migrate blog comments

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/mango-is-website#34]
livefyre comments are not user-friendly at all, and the platform does not seem to be evolving. Another solution should be used instead, and existing comments migrated.
- [ ] identify a suitable comments solution: user-friendly, easy login/auth for users, protected from spam (disqus?)
- [ ] determine the most appropriate migration strategy:
- actually transfer comments to the new platform, 
- or (worst-case scenario): keep them as plain html in the posts
- [ ] actually migrate the comments

**Comment by mef** [comment]
@blueclock do you have any suggestion for a stable and user-friendly commenting solution?

**Comment by blueclock** [comment]
I've only ever used Disqus or CMS native offerings. I can look into Hexo
specific options if you want.

**Comment by mef** [comment]
I don't have the impression that hexo offers anythign like that, plugin search didn't return any result. 

Moreover, I wouldn't like to force visitors to create new accounts to post comments. With Disqus, they could use their existing ones...

**Comment by blueclock** [comment]
So does this mean you are in favour of using Disqus?

----------------------------------------------------------
-----------------------------

**   My LinkedIn <http://www.linkedin.com/in/blueclock> |
Blog gilbertwest.com <http://gilbertwest.me> | Twitter @blueclock
<https://twitter.com/blueclock> **

----------------------------------------------------------
-----------------------------

**Comment by mef** [comment]
yes :)

**Comment by blueclock** [comment]
It's now called Engage.
I'll check that they don't add "17 Things you didn't know about BI"
articles into your comment stream

----------------------------------------------------------
-----------------------------

**   My LinkedIn <http://www.linkedin.com/in/blueclock> |
Blog gilbertwest.com <http://gilbertwest.me> | Twitter @blueclock
<https://twitter.com/blueclock> **

----------------------------------------------------------
-----------------------------

**Comment by mef** [comment]
canceled. No comments :/
