### ISSUE TITLE
modal and contact form

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/mango-is-website#42]
- [x] ~~some modal mechanism should be integrated.~~ postponed
- [x] contact page should contain a contact form
- [x] ~~all other pages should contain the same contact form hidden by default, displayed inside a modal whenever needed~~ postponed
- [x] display of the contact form modal should degrade gracefully by redirecting to contact page, for visitors without javascript
- [x] classic form handling requirements: user-friendliness, validation, graceful errors management, honeypot etc.

**Comment by mef** [comment]
solution for modal: perhaps this one: https://github.com/thephuse/vanilla-modal

**Comment by mef** [comment]
pending: use responsive columns classes to fix small table layouts: columns should collapse earlier

**Comment by mef** [comment]
@blueclock Whenever you have the occasion, thanks for checking that the contact page and form are working ok:

* usability
* shouldn't crash the server (even if you don't define a valid sender's email/pass inside params.json)
* should save a backup of the contact messages in directory `/persist`

**Comment by blueclock** [comment]
@mef One a completed form I get a success notification on send.

Message persists correctly

Client side validation works for required fields
Client side validation works for email type field

Trigger does not seem to work. I tried going from Get A Quote on Corporate Business Intelligence but this was not persisted to trg

I receive this error in my terminal

error sending email
{ [Error: Invalid login: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/answer/14257 bh4sm43513470wjc.43 - gsmtp]
  code: 'EAUTH',
  response: '535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/answer/14257 bh4sm43513470wjc.43 - gsmtp',
  responseCode: 535 }

**Comment by blueclock** [comment]
@mef I would wrap the contact feedback in 

<div class="row">
<div class="ten columns offset-by-two">

</div>
</div>
like the button . Looks neater
