### ISSUE TITLE
site footer

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/mango-is-website#44]
* migrate website footer from branch `master` to branch `hexo-wip`
* style footer in a suitable way (desaturated) -- > in skeleton framework
* structure to be defined inside `footer.ejs` view partial, with some hard-coded content
* list of links to main pages to be retrieved from the theme's config

e.g.

````
        <% for (var i in theme.menu){ %>
          <a href="<%- url_for(theme.menu[i]) %>"><%= i %></a>
        <% } %>
````

P.S. menu's location may be moved from theme to site config, where it's better placed (more related to the site's content than appearance).

**Comment by blueclock** [comment]
New system _data folder created in source/_data.
I recommend renaming source/data to something like blog_data

**Comment by mef** [comment]
Thanks @blueclock , I've just renamed the directory `data` to `blogData`, and adapted related blog post.

I'll do some changes to the footer styling if that's ok for you.

**Comment by mef** [comment]
I'm done :)
