### ISSUE TITLE
switch from Bootstrap to Foundation

### ISSUE THREAD

**Issue by mef** [Mango-information-systems/mango-is-website#6]
* update site structure and style
* ~~use a [git submodule](http://git-scm.com/docs/git-submodule)~~ #19
* work in branch 0.0.3-wip
* custom colors and style: to be discussed
* pages and blog articles layout must still be working

**Comment by webketje** [comment]
As for 'use a github submodule'; because this seemed to be complicated and you were going to take care of it, I've included standard downloaded versions of the scripts in my working directory (testing)

**Comment by mef** [comment]
indeed, I'll take care of it (#19)

**Comment by webketje** [comment]
@mef Full 'base' migration to foundation is done. Let the Sass episode begin?

**Comment by mef** [comment]
there seems to be a regression in the blog index pages: hyperlinks to the blog articles are incorrect and 404. For some reason they include the date inside permalinks

**Comment by mef** [comment]
Good work overall.

* It looks like `/contact/default.cfm` still contains bootstrap syntax
* same for `/tools/csv-to-json/` (some may be in javascript templates?)
* javascript is broken here: http://localhost:4000/blog/business/Belgians-twitter-and-klout.html
* javascript is broken there: http://localhost:4000/blog/business/finding-twitter-influencers-comparing-klout-kred-and-peerindex.html

**Comment by webketje** [comment]
Ah, good catches, I didn't know what to do with the .cfm files (can't test them locally unless I rename to .html and make some changes) & didn't bother with the blog JS. I'll update status here as I move on with these.

**Comment by webketje** [comment]
Status update:
- Sticky nav working now => had to include foundation-bundled version of `modernizr.js`
- Foundation tooltips unfortunately don't allow much JS config, most has to be put on the elements with `data` attributes and classes (this is in relation to blog article Belgians, Twitter and Klout)
- 3/4 of HTML (also in JS templates) of the csv tool is migrated

**Comment by webketje** [comment]
On the second article, the page is also broken on mango-is, see: [Finding twitter influencers Comparing Klout, Kred and peerIndex](http://mango-is.com/blog/business/finding-twitter-influencers-comparing-klout-kred-and-peerindex.html). Error:
`Uncaught TypeError: Cannot read property 'journalists' of undefined(anonymous function) @ 2013-10-08-finding-twitter-influencers-comparing-klout-kred-and-peerindex.js:101`

**Comment by mef** [comment]
canceled - skeleton to be used instead
